# -*- coding: utf-8 -*-
"""필수과제1_강민지28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P2F3Lgc4OXY5Po-ZqrpRG7-g5Ei2ZzZv

## 필수과제1
- y값에 따른 타이타닉데이터들의 피처들의 관계를 정리해 주세요!
- 가설을 세우고, 여성이 생존율이 높을 것이다 이런 것들
- 피처들을 시각적으로도 확인하고, 기초통계적으로도 확인하여서
- 실제로 내가 생각하는 생존과의 중요한 피처는 무엇인지를 정리해 주세요!
- 최소한 가설은 3개 이상으로 잡아서 진행해 주세요!
- 위에서 배운, groupby를 통한 생존에 대한 값 계산, 시각화까지 진행
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dt = sns.load_dataset('titanic')

dt

### 1. pclass가 높은 사람들의 생존율이 높을 것이다.
dt[['pclass', 'survived']].groupby('pclass').sum().sort_values(by='survived', ascending=False)

g1 = sns.FacetGrid(dt, col='pclass')
g1.map(plt.hist, 'survived')

# titanic 데이터에서 survived 의 0 값은 사망, 1 값은 생존을 의미하므로
# 상대적으로 pclass=3인 데이터의 사망률이 높은 것을 시각적으로 확인할 수 있고,
# 상대적으로 pclass=1인 데이터의 생존률이 높은 것을 시각적으로 확인할 수 있으므로
# 처음 세운 가설인 "pclass"가 높은 사람들의 생존율이 더 높을 것이라는 가설은 맞다고 할 수 있다.

### 2. 승선한 지역(embark_town)과 생존은 관계가 있을 것이다.

dt[['embark_town', 'survived']].groupby('embark_town').sum().sort_values(by='survived', ascending=False)

g2 = sns.FacetGrid(dt, col='embark_town')
g2.map(plt.hist, 'survived')

# 일단, 위의 통계적 수치나, 그래프를 보면 알 수 있듯이 승선지역에 따른
# 생존율의 차이가 나타난다.

# Southampton: 생존율이 높지만, 그만큼 사망률도 굉장히 높다.
# Cherbourg: 생존율은 세 지역 중 두 번째이고, 사망률도 낮은 편이다.
# Queenstown: 생존율, 사망률 둘 다 낮다.

### 3. (2)에서 승선한 지역이 생존과 관계있는 이유는, 승선한 지역 내에 분포하는 성별 혹은 나이 때문일까?
dt[['embark_town', 'age', 'sex']].groupby(['embark_town', 'sex']).mean().sort_values(by='age', ascending=False)

dt.value_counts('embark_town', ascending=False)

dt.groupby(['embark_town', 'sex'])['survived'].sum()
# embark_town & sex 별 생존자 수

dt.groupby(['embark_town', 'sex'])['survived'].count()
# 전체 성별 분포

g3 = sns.FacetGrid(dt, col='embark_town')
g3.map(sns.pointplot, 'age', 'sex')

# 그림만 봤을 땐, Southampton의 성별마다의 나이 평균분포가 적어서
# 자연스레 해당 지역의 생존율이 높지 않을까? 라고 예측할 수도 있겠지만
# groupby를 통해 분석해 본 아래의 각각의 분석 결과를 보면...

# Southampton: 생존율이 높지만, 그만큼 사망률도 굉장히 높다.
# Cherbourg: 생존율은 세 지역 중 두 번째이고, 사망률도 낮은 편이다.
# Queenstown: 생존율, 사망률 둘 다 낮다.

# Southampton: 644명으로 인원이 가장 많다.
# Cherbourg: 168명으로 인원이 중간이다.
# Queenstown: 77명으로 인원이 가장 적다.

# Cherbourg	male	32.998841
#           female	28.344262
# Queenstown male	30.937500
#            female	24.291667
# Southampton male	30.291440
#             female 27.771505

# 성별 분포
'''
embark_town  sex
Cherbourg    female     73
             male       95
Queenstown   female     36
             male       41
Southampton  female    203
             male      441
'''

# 생존자 수
'''
embark_town  sex
Cherbourg    female     64
             male       29
Queenstown   female     27
             male        3
Southampton  female    140
             male       77
'''

# 총 인원으로 보면 Southampton: 644명으로 인원이 가장 많다.
#                  Queenstown: 77명으로 인원이 가장 적다.

# 지역별/성별 나이 평균으로 보면, Queenstown이 가장 평균 나이가 적다.
#                                 Cherbourg가 가장 평균 나이가 많다.

# Southampton: 생존율이 높지만, 그만큼 사망률도 굉장히 높다.
# Queenstown: 생존율, 사망률 둘 다 낮다.

# 결론: 생존율이 가장 높은 Southampton은 생존율이 높은 편이지만,
#       전체 인원의 수가 압도적으로 많으므로
#       해당 지역의 성별의 분포(남성이 여성보다 많음), 나이 분포(평균 연령은 Queenstown이 가장 낮음)
#       등이 미치는 영향이 미비하다고 볼 수 있다.
#       따라서 전체 인원이 압도적으로 많은 Southampton의 생존율에
#       처음에 가정했던 성별 분포, 나이 분포가 영향을 미치는지에 대해서는
#       정확하게 판단할 수 없다.

### 4. 남성이 여성보다 생존률이 낮을 것이다.
#      남성이 여성 또는 노인을 구조하는데 힘썼을 것으로 추정: 이 부분에 대해서는 알 수 없음

dt[['sex', 'survived']].groupby('sex').sum().sort_values(by='survived', ascending=False)

g4 = sns.FacetGrid(dt, col='sex')
g4.map(plt.hist, 'survived')

# 남성의 사망률이 여성보다 높고, 여성의 생존율이 남성보다 높음을 알 수 있다.

### 5. 요금을 많이 낸 사람들이 pclass 가 높을 가능성이 크고, 이는 생존과 직결될 것이다.

dt[['pclass', 'fare']].groupby('pclass').mean().sort_values(by='fare', ascending=False)

g5 = sns.FacetGrid(dt, col='pclass')
g5.map(plt.hist, 'fare')

# 위의 결과를 통해 pclass가 높을 수록 요금이 높은 것을 알 수 있다.
# 이는 생존과도 직결이 되는 것일까?

dt[['pclass', 'fare', 'survived']].groupby(['pclass', 'survived']).mean().sort_values(by='fare', ascending=False)

g6 = sns.FacetGrid(dt, col='pclass', row='survived')
g6.map(sns.barplot, 'sex','fare')

# 위의 통계치와 그래프로 추정해볼 때, pclass는 요금과 관련이 있고,
# 요금이 높고, pclass가 높은 사람들은 생존율도 높음을 알 수 있다.
# 즉, 요금과 pclass가 관련이 있고, 이는 생존율과도 관련이 있다.

# 결과적으로 정리해보면, 내가 생각하는 '생존'과 관련이 있고, 직결되는 피쳐는
# pclass~요금, 나이, 성별, 승선하는 지역이라고 생각하였고,
# 각각이 생존과 어떤 연관성이 있는지 알아보기 위해 위의 가설을 통해 검증하였다.